import type { Monaco } from '@monaco-editor/react';

export const defineEntropyTheme = (monaco: Monaco) => {
  monaco.editor.defineTheme('entropy-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '52525b', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ffffff', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'ffffff', fontStyle: 'bold' },
      { token: 'string', foreground: 'a1a1aa' },
      { token: 'string.escape', foreground: 'd4d4d8' },
      { token: 'number', foreground: 'e4e4e7' },
      { token: 'number.float', foreground: 'e4e4e7' },
      { token: 'type', foreground: 'd4d4d8' },
      { token: 'type.identifier', foreground: 'ffffff' },
      { token: 'class', foreground: 'ffffff' },
      { token: 'function', foreground: 'ffffff' },
      { token: 'function.call', foreground: 'ededed' },
      { token: 'variable', foreground: 'd4d4d8' },
      { token: 'variable.parameter', foreground: 'a1a1aa' },
      { token: 'operator', foreground: '71717a' },
      { token: 'delimiter', foreground: '71717a' },
      { token: 'tag', foreground: 'a1a1aa' },
    ],
    colors: {
      'editor.background': '#000000',
      'editor.foreground': '#EDEDED',
      'editorCursor.foreground': '#FFFFFF',
      'editor.lineHighlightBackground': '#0d0d0d',
      'editorLineNumber.foreground': '#333333',
      'editorLineNumber.activeForeground': '#EDEDED',
      'editor.selectionBackground': '#262626',
      'editor.inactiveSelectionBackground': '#171717',
      'editor.selectionHighlightBackground': '#1f1f1f',
      'editorGutter.background': '#000000',
      'editorWidget.background': '#080808',
      'editorWidget.border': '#222222',
      'editorSuggestWidget.background': '#080808',
      'editorSuggestWidget.border': '#222222',
      'editorSuggestWidget.selectedBackground': '#181818',
      'editorSuggestWidget.highlightForeground': '#FFFFFF',
      'editorHoverWidget.background': '#080808',
      'editorHoverWidget.border': '#222222',
      'input.background': '#050505',
      'input.border': '#222222',
      'input.foreground': '#EDEDED',
      'scrollbarSlider.background': '#22222266',
      'scrollbarSlider.hoverBackground': '#33333399',
      'scrollbarSlider.activeBackground': '#444444cc',
    },
  });
};
